/** PINs are 8 digits (Module 12), generated by the server and shown once as `1234 5678`. */
export const PIN_LENGTH = 8

/** Keeps the digits of typed or pasted text (spaces, dashes and anything else dropped), at most 8. */
export const pinDigits = (text: string): string => text.replace(/\D/g, '').slice(0, PIN_LENGTH)

/** `12345678` -> `1234 5678`. */
export const formatPin = (pin: string): string => (pin.length > 4 ? `${pin.slice(0, 4)} ${pin.slice(4)}` : pin)
