/**
 * All user-facing copy lives here so Sinhala/Tamil can be added later
 * (turn `strings` into a per-locale lookup; call sites stay the same).
 */
export const strings = {
  app: { name: 'ConvoyPass', tagline: 'Contractor vehicle gate passes' },

  common: {
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    create: 'Create',
    edit: 'Edit',
    done: 'Done',
    retry: 'Try again',
    loading: 'Loading…',
    copy: 'Copy',
    copied: 'Copied',
    signOut: 'Sign out',
    all: 'All',
    optional: 'optional',
    actions: 'Actions',
    status: 'Status',
    none: '—',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    somethingWrong: 'Something went wrong. Please try again.',
    loadFailed: 'Could not load data.',
  },

  roles: {
    admin: 'Admin',
    officer: 'Officer',
    supervisor: 'Supervisor',
    driver: 'Driver',
    security: 'Security',
  },

  status: { active: 'Active', disabled: 'Disabled', suspended: 'Suspended' },

  auth: {
    signInTitle: 'Sign in',
    staffTab: 'Staff',
    driverTab: 'Driver',
    modeLabel: 'Account type',
    email: 'Email',
    password: 'Password',
    phone: 'Phone number',
    phoneHint: '07X XXX XXXX',
    pin: '6-digit PIN',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    invalidEmail: 'Enter a valid email',
    invalidPhone: 'Enter a valid mobile number, e.g. 0771234567',
    invalidPin: 'PIN must be 6 digits',
    passwordRequired: 'Enter your password',
    changePasswordTitle: 'Set a new password',
    changePinTitle: 'Set a new PIN',
    changePasswordIntro: 'For your security, choose a new password before continuing.',
    changePinIntro: 'For your security, choose a new 6-digit PIN before continuing.',
    newPassword: 'New password',
    newPin: 'New 6-digit PIN',
    confirmPassword: 'Confirm password',
    confirmPin: 'Confirm PIN',
    passwordTooShort: 'Use at least 8 characters',
    passwordMismatch: 'Passwords do not match',
    pinMismatch: 'PINs do not match',
    updatePassword: 'Update password',
    updatePin: 'Update PIN',
    passwordUpdated: 'Password updated',
    pinUpdated: 'PIN updated',
    redirecting: 'Signing you in…',
  },

  authErrors: {
    invalidCredentials: 'Incorrect details. Please check and try again.',
    accountUnavailable: 'This account is unavailable. Contact your administrator.',
    tooManyAttempts: 'Too many attempts. Please wait a moment and try again.',
    network: 'Network problem. Check your connection and try again.',
    generic: 'Could not sign in. Please try again.',
    accountDisabled: 'Your account has been disabled. Contact your administrator.',
    accountMissing: 'Your account is not set up. Contact your administrator.',
    contractorSuspended: 'Your company account is suspended. Contact your administrator.',
    sessionEnded: 'Your session ended. Please sign in again.',
    recentLoginRequired: 'Please sign in again, then change your password.',
  },

  // Keyed by the `details.reason` returned by Cloud Functions.
  apiErrors: {
    unauthenticated: 'Please sign in again.',
    'caller-not-active': 'Your account cannot perform this action.',
    forbidden: 'You are not allowed to do that.',
    'invalid-input': 'Some details are invalid. Please check and try again.',
    'tenant-mismatch': 'That record belongs to a different organisation.',
    'user-not-found': 'User not found.',
    'contractor-invalid': 'Choose an active contractor.',
    'email-exists': 'That email is already registered.',
    'phone-exists': 'That phone number is already registered.',
    'self-status': 'You cannot disable your own account.',
    'self-reset': 'Use “Change password” for your own account.',
    'recent-login-required': 'Please sign in again, then change your password.',
    'plate-exists': 'A vehicle with this plate number already exists.',
    'vehicle-not-found': 'Vehicle not found.',
    'driver-invalid': 'Choose active drivers that belong to this contractor.',
    'contractor-not-found': 'Contractor not found.',
    'photo-path-invalid': 'That photo location is not valid.',
    internal: 'Something went wrong. Please try again.',
  },

  home: {
    welcome: (name: string) => `Hello, ${name}`,
    role: 'Role',
    contractor: 'Contractor',
    placeholder: 'This area is coming soon.',
  },

  vehicle: { title: 'Vehicle', placeholder: (id: string) => `Vehicle ${id} — details coming soon.` },

  list: {
    count: (shown: number, total: number) => (shown === total ? `${total}` : `${shown} of ${total}`),
    capNotice: (n: number) => `Showing the first ${n} records. Narrow the list with search or filters.`,
    allStatuses: 'All statuses',
    allContractors: 'All contractors',
    noMatchTitle: 'Nothing matches',
    noMatchBody: 'Try a different search or clear the filters.',
    clearFilters: 'Clear filters',
    showMore: (n: number) => `Show more (${n})`,
  },

  vehicles: {
    title: 'Vehicles',
    add: 'Add vehicle',
    edit: 'Edit vehicle',
    searchPlaceholder: 'Search plate, make or driver',
    searchLabel: 'Search vehicles',
    emptyTitle: 'No vehicles yet',
    emptyBody: 'Add a vehicle to generate its permanent QR code.',
    columns: { plate: 'Plate', type: 'Type', contractor: 'Contractor', drivers: 'Drivers', status: 'Status' },
    noDrivers: 'No drivers assigned',
    form: {
      plate: 'Plate number',
      plateHint: 'e.g. WP LJ-4821, NP KA 1234, CAB-1234',
      saveAs: 'Will be saved as',
      type: 'Vehicle type',
      typePlaceholder: 'Select a type',
      makeModel: 'Make and model',
      contractor: 'Contractor',
      contractorPlaceholder: 'Select a contractor',
      drivers: 'Assigned drivers',
      driversEmpty: 'No active drivers for this contractor yet.',
      driversPickContractor: 'Select a contractor to choose drivers.',
      submit: 'Create vehicle',
      created: 'Vehicle created',
      updated: 'Vehicle updated',
    },
    errors: {
      plate: 'Enter 4 to 12 letters or numbers',
      type: 'Choose a vehicle type',
      makeModel: 'Keep make and model under 60 characters',
      contractor: 'Select a contractor',
      duplicateInFile: 'Duplicate plate in this file',
    },
    drawer: {
      qrTitle: 'Vehicle QR',
      downloadPng: 'Download PNG',
      downloadSvg: 'Download SVG',
      copyLink: 'Copy link',
      linkCopied: 'Link copied',
      print: 'Print label',
      drivers: 'Assigned drivers',
      editDrivers: 'Edit drivers',
      saveDrivers: 'Save drivers',
      driversSaved: 'Drivers updated',
      suspend: 'Suspend vehicle',
      activate: 'Activate vehicle',
      suspendTitle: 'Suspend this vehicle?',
      activateTitle: 'Activate this vehicle?',
      suspendBody: (plate: string) => `${plate} will be marked suspended. Its QR code stays valid, but it cannot be used for new passes.`,
      activateBody: (plate: string) => `${plate} will be active again.`,
      suspended: 'Vehicle suspended',
      activated: 'Vehicle activated',
      permanentId: 'QR ID',
    },
    import: {
      button: 'Import CSV',
      title: 'Import vehicles',
      template: 'Download template',
      pickContractor: 'Select the contractor these vehicles belong to.',
      chooseFile: 'Choose a CSV file',
      hint: 'Columns: plateNo, type, makeModel. Up to 2000 rows.',
      parsing: 'Reading file…',
      fileEmpty: 'No rows found in this file.',
      headerError: 'The file needs plateNo and type columns.',
      tooMany: (n: number) => `Only the first ${n} rows are used.`,
      previewTitle: 'Preview',
      valid: (n: number) => `${n} valid`,
      invalid: (n: number) => `${n} with errors`,
      rowCol: 'Row',
      statusCol: 'Result',
      ok: 'Ready',
      importValid: (n: number) => `Import ${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
      importing: 'Importing…',
      nothingValid: 'There are no valid rows to import.',
      summaryTitle: 'Import finished',
      imported: (n: number) => `${n} imported`,
      failed: (n: number) => `${n} failed`,
      downloadFailed: 'Download failed rows',
      another: 'Import another file',
      rowErrors: {
        'invalid-plate': 'Invalid plate number',
        'invalid-type': 'Unknown vehicle type',
        'invalid-make-model': 'Make and model too long',
        'plate-exists': 'Plate already exists',
        internal: 'Could not save this row',
      },
    },
  },

  drivers: {
    title: 'Drivers',
    add: 'Add driver',
    edit: 'Edit driver',
    searchPlaceholder: 'Search name, phone or vehicle',
    searchLabel: 'Search drivers',
    emptyTitle: 'No drivers yet',
    emptyBody: 'Add a driver so they can be assigned to vehicles.',
    columns: { driver: 'Driver', phone: 'Phone', vehicles: 'Vehicles', status: 'Status' },
    noVehicles: 'No vehicles assigned',
    form: {
      name: 'Full name',
      phone: 'Mobile number',
      contractor: 'Contractor',
      contractorPlaceholder: 'Select a contractor',
      licenseNo: 'Licence number',
      pin: 'Temporary 6-digit PIN',
      generate: 'Generate',
      photo: 'Photo',
      takePhoto: 'Take or choose photo',
      changePhoto: 'Change photo',
      removeSelected: 'Remove',
      photoHint: 'Optional. Resized and compressed before upload.',
      photoFailed: 'Could not use that photo. Try another one.',
      nameRequired: 'Enter a name',
      contractorRequired: 'Select a contractor',
      pinTrivial: 'Choose a PIN that is harder to guess',
      submit: 'Create driver',
      created: 'Driver created',
      updated: 'Driver updated',
      photoUploadFailed: 'Driver saved, but the photo could not be uploaded. Edit the driver to try again.',
    },
    credentials: {
      title: 'Share sign-in details',
      warning: 'This is the only time the PIN is shown. The driver must change it on first sign-in.',
      phone: 'Phone',
      pin: 'PIN',
      copy: 'Copy details',
      copied: 'Details copied',
      whatsapp: 'Share on WhatsApp',
      message: (appUrl: string, phone: string, pin: string) =>
        `Welcome to ConvoyPass.\nSign in at ${appUrl}\nPhone: ${phone}\nPIN: ${pin}\nYou must change your PIN the first time you sign in.`,
      copyText: (appUrl: string, phone: string, pin: string) =>
        `ConvoyPass\n${appUrl}\nPhone: ${phone}\nPIN: ${pin}`,
    },
    resetPin: 'Reset PIN',
    disable: 'Disable',
    enable: 'Enable',
    disableTitle: 'Disable this driver?',
    enableTitle: 'Enable this driver?',
    disableBody: (name: string) => `${name} will be signed out and cannot sign in. They are also removed from new vehicle assignments.`,
    enableBody: (name: string) => `${name} will be able to sign in again.`,
    disabled: 'Driver disabled',
    enabled: 'Driver enabled',
    photoAlt: (name: string) => `Photo of ${name}`,
  },

  qr: {
    title: 'QR labels',
    devBanner: 'Dev link: do not print',
    devBannerBody: (url: string) => `QR codes currently point to ${url}. Labels printed now will not work in production.`,
    missingBase: 'VITE_APP_BASE_URL is not set, so QR codes cannot be generated.',
    missingBaseBody: 'Set VITE_APP_BASE_URL in the web app environment (see .env.example) and rebuild.',
    selection: 'Vehicles',
    selectAll: 'All vehicles',
    selectContractor: 'By contractor',
    selectManual: 'Pick vehicles',
    contractor: 'Contractor',
    size: 'Label size',
    sizeLarge: 'Large (90 mm, 6 per page)',
    sizeSmall: 'Small (50 mm, 15 per page)',
    print: 'Print',
    selected: (n: number) => `${n} selected`,
    labelCount: (n: number) => `${n} ${n === 1 ? 'label' : 'labels'}`,
    noneSelected: 'Select at least one vehicle to print.',
    preview: 'Preview',
    activeOnly: 'Suspended vehicles are not included unless picked by hand.',
    selectVisible: 'Select all shown',
    clearSelection: 'Clear',
    brand: 'ConvoyPass',
  },

  supervisor: {
    nav: { home: 'Home', vehicles: 'Vehicles', drivers: 'Drivers', qr: 'QR' },
    mainNav: 'Main navigation',
    vehicles: 'Vehicles',
    drivers: 'Drivers',
    quickActions: 'Quick actions',
    approvalsTitle: 'Approvals',
    approvalsBody: 'Passes waiting for your approval will appear here.',
    noContractor: 'Your account is not linked to a contractor. Contact your administrator.',
  },

  errorPages: {
    forbiddenTitle: '403 — Access denied',
    forbiddenBody: 'You do not have permission to view this page.',
    notFoundTitle: '404 — Page not found',
    notFoundBody: 'The page you are looking for does not exist.',
    goHome: 'Go to my home',
    signInRequired: 'Go to sign in',
  },

  admin: {
    nav: { users: 'Users', contractors: 'Contractors', vehicles: 'Vehicles', drivers: 'Drivers', qr: 'QR labels' },
    panel: 'Admin',
    users: {
      title: 'Users',
      create: 'Create user',
      searchPlaceholder: 'Search name, email or phone',
      searchLabel: 'Search users',
      roleFilter: 'Role',
      statusFilter: 'Status',
      emptyTitle: 'No users found',
      emptyBody: 'Try changing the filters, or create a user.',
      columns: { name: 'Name', role: 'Role', login: 'Email / phone', contractor: 'Contractor', status: 'Status' },
      mustChange: 'Must change password',
      count: (n: number) => `${n} ${n === 1 ? 'user' : 'users'}`,
    },
    createUser: {
      title: 'Create user',
      role: 'Role',
      name: 'Full name',
      email: 'Email',
      phone: 'Phone number',
      contractor: 'Contractor',
      contractorPlaceholder: 'Select a contractor',
      noContractors: 'Create an active contractor first.',
      password: 'Temporary password',
      pin: 'Temporary 6-digit PIN',
      generate: 'Generate',
      nameRequired: 'Enter a name',
      contractorRequired: 'Select a contractor',
      submit: 'Create user',
      created: 'User created',
      credentialsTitle: 'Share these credentials',
      credentialsWarning: 'This is the only time they are shown. The user must change them on first sign-in.',
      loginId: 'Sign-in',
      secretPassword: 'Password',
      secretPin: 'PIN',
      copyCredentials: 'Copy credentials',
      credentialsCopied: 'Credentials copied',
    },
    editUser: { title: 'Edit user', name: 'Full name', phone: 'Phone number', updated: 'User updated' },
    reset: {
      title: 'Reset credential',
      resetPassword: 'Reset password',
      resetPin: 'Reset PIN',
      newPassword: 'New temporary password',
      newPin: 'New temporary 6-digit PIN',
      submit: 'Reset',
      done: 'Credential reset',
      forUser: (name: string) => `Set a new temporary credential for ${name}. They must change it on next sign-in.`,
    },
    toggle: {
      disable: 'Disable',
      enable: 'Enable',
      disableTitle: 'Disable this user?',
      enableTitle: 'Enable this user?',
      disableBody: (name: string) => `${name} will be signed out and will not be able to sign in.`,
      enableBody: (name: string) => `${name} will be able to sign in again.`,
      disabled: 'User disabled',
      enabled: 'User enabled',
    },
    contractors: {
      title: 'Contractors',
      create: 'New contractor',
      edit: 'Edit contractor',
      name: 'Company name',
      contactName: 'Contact person',
      phone: 'Phone',
      nameRequired: 'Enter a name',
      emptyTitle: 'No contractors yet',
      emptyBody: 'Create a contractor to add supervisors and drivers.',
      address: 'Address',
      notes: 'Notes',
      searchPlaceholder: 'Search contractors',
      searchLabel: 'Search contractors',
      statusFilter: 'Status',
      columns: { name: 'Name', contact: 'Contact', vehicles: 'Vehicles', drivers: 'Drivers', status: 'Status' },
      suspend: 'Suspend',
      activate: 'Activate',
      suspendTitle: 'Suspend this contractor?',
      activateTitle: 'Activate this contractor?',
      suspendBody: (name: string) =>
        `${name} will be suspended. Every supervisor and driver of this contractor is signed out immediately and cannot sign in until it is activated again. No data is deleted.`,
      activateBody: (name: string) =>
        `${name} will be active again and its users can sign in. Users who were disabled individually stay disabled.`,
      back: 'Contractors',
      notFound: 'Contractor not found.',
      summary: 'Summary',
      createdOn: 'Created',
      supervisors: 'Supervisors',
      noSupervisors: 'No supervisors yet.',
      noVehicles: 'No vehicles yet.',
      noDrivers: 'No drivers yet.',
      vehicleCount: (n: number) => `${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
      driverCount: (n: number) => `${n} ${n === 1 ? 'driver' : 'drivers'}`,
      viewAll: 'View all',
      open: 'Open',
      created: 'Contractor created',
      updated: 'Contractor updated',
      suspended: 'Contractor suspended',
      activated: 'Contractor activated',
    },
  },
} as const
