/**
 * All user-facing copy lives here so Sinhala/Tamil can be added later
 * (turn `strings` into a per-locale lookup; call sites stay the same).
 */
export const strings = {
  app: { name: 'ConvoyPass', tagline: 'Contractor vehicle gate passes' },

  common: {
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    create: 'Create',
    edit: 'Edit',
    done: 'Done',
    retry: 'Try again',
    loading: 'Loading…',
    copy: 'Copy',
    copied: 'Copied',
    signOut: 'Sign out',
    all: 'All',
    optional: 'optional',
    actions: 'Actions',
    status: 'Status',
    none: '—',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    somethingWrong: 'Something went wrong. Please try again.',
    loadFailed: 'Could not load data.',
    dismiss: 'Dismiss',
  },

  /** Why a list or page could not load, chosen from the Firestore / Functions error code (see describeLoadError). */
  loadErrors: {
    permission: "This account isn't allowed to read this data. Sign out and back in. If it keeps happening, ask your ConvoyPass administrator to check that the Firestore security rules are deployed.",
    index: "This view needs a database index that hasn't been built yet. Ask your ConvoyPass administrator to deploy the Firestore indexes (it can take a few minutes to finish building).",
    network: "Can't reach the server. Check your connection and try again.",
    session: 'Your session has expired. Please sign in again.',
    quota: 'The service is busy right now. Wait a moment and try again.',
    missingConfig: 'The app is not connected to a Firebase project. Add the VITE_FIREBASE_* settings to the build, then rebuild and redeploy.',
    missingConfigKeys: (keys: string) => `Missing settings: ${keys}.`,
  },

  updates: { ready: 'Update ready, reload when convenient', reload: 'Reload' },

  notifications: {
    bell: 'Notifications',
    bellUnread: (n: number) => `Notifications, ${n} unread`,
    panelTitle: 'Notifications',
    empty: 'Nothing yet. Alerts about passes show up here.',
    loadFailed: 'Could not load notifications.',
    markAllRead: 'Mark all read',
    seeAll: 'See all',
    unread: 'Unread',
    justNow: 'just now',
    pageTitle: 'Notifications',
    loadMore: 'Load older',
    noMore: 'That is everything.',
    back: 'Back',
    settings: 'Alert settings',
    markFailed: 'Could not update that notification.',
    types: {
      approval_needed: 'Approval needed',
      resubmitted: 'Resubmitted',
      awaiting_officer: 'Awaiting officer',
      pass_approved: 'Approved',
      pass_rejected: 'Rejected',
      pass_rejected_info: 'Rejected',
      checked_in: 'Checked in',
      entry_denied: 'Entry denied',
      sla_overdue: 'Overdue',
    },
  },

  push: {
    cardTitle: 'Get alerts for approvals',
    cardBody: 'Get a message on this phone when a pass needs you, is approved, or is rejected, even when the app is closed.',
    enable: 'Enable',
    enabling: 'Enabling…',
    notNow: 'Not now',
    dismiss: 'Dismiss',
    enabledToast: 'Alerts are on for this device.',
    deniedToast: 'Alerts are blocked. Allow notifications for this site in your browser settings.',
    failedToast: 'Could not turn on alerts. Try again later.',
    iosTitle: 'Add to Home Screen to enable alerts',
    iosBody: 'On iPhone and iPad, alerts only work once ConvoyPass is installed on your Home Screen.',
    iosSteps: ['Tap the Share button in Safari.', 'Choose “Add to Home Screen”.', 'Open ConvoyPass from your Home Screen, then turn on alerts.'],
    unsupported: 'This browser does not support alerts.',
    settingsTitle: 'Alert settings',
    deviceTitle: 'This device',
    toggle: 'Alerts on this device',
    statusOn: 'On',
    statusOff: 'Off',
    permissionGranted: 'Allowed in your browser settings',
    permissionDenied: 'Blocked in your browser settings. Allow notifications for this site there, then turn alerts on here.',
    permissionDefault: 'Not asked yet. Turn alerts on to be asked.',
    otherDevices: 'Alerts are set up per device. Sign in on another device to manage it there.',
    needsConfig: 'Alerts are not configured for this environment.',
  },

  audit: {
    nav: 'Audit log',
    title: 'Audit log',
    intro: 'Who did what, newest first. Entries cannot be edited or deleted.',
    from: 'From',
    to: 'To',
    actor: 'Actor',
    actorPlaceholder: 'Search people…',
    anyActor: 'Anyone',
    action: 'Action',
    anyAction: 'Any action',
    targetType: 'Target type',
    anyTarget: 'Any target',
    apply: 'Apply',
    clear: 'Clear filters',
    time: 'Time',
    summary: 'Summary',
    target: 'Target',
    empty: 'No entries match these filters.',
    loadFailed: 'Could not load the audit log.',
    olderPage: 'Older',
    newerPage: 'Newer',
    page: (n: number) => `Page ${n}`,
    exportCsv: 'Export CSV',
    exportNote: 'Exports the entries matching the current filters (up to 5,000).',
    exporting: 'Exporting…',
    exported: (n: number) => `Exported ${n} entries.`,
    detailTitle: 'Audit entry',
    meta: 'Details',
    noMeta: 'No extra details.',
    system: 'System',
    unknownUser: 'Unknown user',
    superAdmin: 'ConvoyPass Super Admin',
    superAdminRole: 'Super admin',
    targets: { user: 'User', vehicle: 'Vehicle', contractor: 'Contractor', tenant: 'Settings', pass: 'Pass', gateEvent: 'Gate event', notification: 'Notification' },
    actions: {
      'user.create': 'User created',
      'user.update': 'User updated',
      'user.disable': 'User disabled',
      'user.enable': 'User enabled',
      'user.resetCredential': 'Credential reset',
      'user.changeOwnPassword': 'Own password changed',
      'vehicle.create': 'Vehicle created',
      'vehicle.update': 'Vehicle updated',
      'vehicle.suspend': 'Vehicle suspended',
      'vehicle.activate': 'Vehicle activated',
      'vehicle.setDrivers': 'Vehicle drivers changed',
      'vehicle.import': 'Vehicles imported',
      'contractor.suspend': 'Contractor suspended',
      'contractor.activate': 'Contractor activated',
      'tenant.settings.update': 'Settings changed',
      'pass.submit': 'Pass submitted',
      'pass.resubmit': 'Pass resubmitted',
      'pass.approve.supervisor': 'Approved by supervisor',
      'pass.approve.officer': 'Approved by officer',
      'pass.reject.supervisor': 'Rejected by supervisor',
      'pass.reject.officer': 'Rejected by officer',
      'pass.revoke': 'Pass revoked',
      'pass.checkIn': 'Checked in',
      'gate.deny': 'Entry denied',
      'evidence.purge': 'Evidence removed (retention)',
      'tenant.created': 'Workspace created',
      'user.created': 'First admin created',
      'admin.recovery': 'Admin account recovered',
    },
  },

  retention: {
    title: 'Evidence retention',
    intro: 'Photos attached to passes can be removed automatically after a number of days. Pass records and their history always stay.',
    keep: 'Keep photos forever (default)',
    removeAfter: 'Remove photos after',
    days: 'days',
    warning: 'Deletion is permanent. Removed photos cannot be recovered, and this applies to every pass older than the limit, including past ones, once you save.',
    range: 'Choose between 30 and 3650 days.',
    saved: 'Retention saved.',
    removed: 'Evidence removed per retention policy',
    confirmTitle: 'Delete old photos permanently?',
    confirmBody: (days: number) => `Photos on passes older than ${days} days will be deleted for good, including photos that are already past that age. Pass records and their history stay.`,
    confirm: 'Delete photos',
  },

  errorBoundary: {
    title: 'Something went wrong',
    body: 'The app hit an unexpected problem. Reloading usually fixes it. Your pass drafts are kept.',
    reload: 'Reload',
    gateTitle: 'This screen hit a problem',
    gateBody: 'Go back to the gate home and try again. Check-ins already queued are safe.',
    gateHome: 'Back to gate',
    formTitle: 'This form hit a problem',
    formBody: 'Your answers are saved on this device. Reload to continue.',
  },

  privacy: {
    title: 'Privacy',
    placeholder: 'The privacy policy for this service will be published here by your organisation.',
    link: 'Privacy',
  },

  userSettings: { title: 'Settings', back: 'Back', alerts: 'Alerts', account: 'Account', signedInAs: 'Signed in as' },

  roles: {
    admin: 'Admin',
    officer: 'Officer',
    supervisor: 'Supervisor',
    driver: 'Driver',
    security: 'Security',
  },

  status: { active: 'Active', disabled: 'Disabled', suspended: 'Suspended' },

  auth: {
    signInTitle: 'Sign in',
    staffTab: 'Staff',
    driverTab: 'Driver',
    modeLabel: 'Account type',
    email: 'Email',
    password: 'Password',
    phone: 'Phone number',
    phoneHint: '07X XXX XXXX',
    pin: '6-digit PIN',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    invalidEmail: 'Enter a valid email',
    invalidPhone: 'Enter a valid mobile number, e.g. 0771234567',
    invalidPin: 'PIN must be 6 digits',
    passwordRequired: 'Enter your password',
    changePasswordTitle: 'Set a new password',
    changePinTitle: 'Set a new PIN',
    changePasswordIntro: 'For your security, choose a new password before continuing.',
    changePinIntro: 'For your security, choose a new 6-digit PIN before continuing.',
    newPassword: 'New password',
    newPin: 'New 6-digit PIN',
    confirmPassword: 'Confirm password',
    confirmPin: 'Confirm PIN',
    passwordTooShort: 'Use at least 8 characters',
    passwordMismatch: 'Passwords do not match',
    pinMismatch: 'PINs do not match',
    updatePassword: 'Update password',
    updatePin: 'Update PIN',
    passwordUpdated: 'Password updated',
    pinUpdated: 'PIN updated',
    redirecting: 'Signing you in…',
    forgotPassword: 'Forgot password?',
    driverForgotHelp: 'Forgot your PIN? Ask your supervisor to reset it.',
  },

  forgot: {
    title: 'Reset your password',
    intro: 'Enter your work email and we will send you a link to choose a new password.',
    send: 'Send reset link',
    sending: 'Sending…',
    sent: "If an account exists for this email, we've sent a reset link.",
    sentHint: 'It can take a few minutes. Check your spam folder too.',
    resend: 'Send again',
    resendIn: (s: number) => `Send again in ${s} s`,
    back: 'Back to sign in',
    driversNote: 'Drivers: ask your supervisor to reset your PIN.',
  },

  authAction: {
    checking: 'Checking your link…',
    resetTitle: 'Choose a new password',
    resetFor: (email: string) => `For ${email}`,
    resetSubmit: 'Save new password',
    resetSaving: 'Saving…',
    resetDoneTitle: 'Password updated',
    resetDone: 'You can now sign in with your new password.',
    verifyTitle: 'Verify your email',
    verifyDoneTitle: 'Email verified',
    verifyDone: 'Thank you. Your email address is confirmed, so you can recover your account if you ever lose your password.',
    linkExpired: 'This link has expired or was already used.',
    linkInvalid: 'This link is not valid.',
    requestNew: 'Request a new reset link',
    verifyNewHint: 'Sign in and use "Resend" in the banner at the top to get a new verification email.',
    goToSignIn: 'Go to sign in',
    openApp: 'Open ConvoyPass',
    userDisabled: 'This account is unavailable. Contact your administrator.',
    network: 'Network problem. Check your connection and try again.',
    generic: 'Something went wrong. Please try again.',
  },

  passwordRules: {
    title: 'Your password must have',
    length: 'At least 10 characters',
    notEmail: 'Not your email address',
    notCommon: 'Not a commonly used password',
    met: 'done',
    unmet: 'not yet',
    mismatch: 'Passwords do not match',
    tooShortPin: 'PIN must be exactly 6 digits',
    weakPin: 'That PIN is too easy to guess. Avoid repeats and sequences like 123456.',
    unacceptable: 'Choose a password that meets every rule below.',
  },

  verifyBanner: {
    message: 'Verify your email so you can recover your account',
    resend: 'Resend',
    resendIn: (s: number) => `Resend in ${s} s`,
    verified: "I've verified",
    sent: 'Verification email sent.',
    stillNot: "We can't see the verification yet. Open the link in the email first.",
    failed: 'Could not send the email. Try again in a moment.',
  },

  setup: {
    title: 'Set up your workspace',
    intro: 'Create your company workspace and your admin account. This link works once.',
    forCompany: (name: string) => `Invitation for ${name}`,
    validating: 'Checking your link…',
    invalidTitle: 'This setup link is invalid or has expired.',
    invalidHelp: 'Ask your ConvoyPass contact for a new link.',
    signedIn: (who: string) => `You're signed in as ${who}. Sign out to set up a new workspace.`,
    signOut: 'Sign out',
    companyName: 'Company name',
    adminName: 'Your full name',
    email: 'Work email',
    emailLocked: 'This invitation is for this email address.',
    password: 'Password',
    confirm: 'Confirm password',
    timezone: 'Timezone',
    timezoneHint: 'Passes use this timezone for "today". Start typing to search.',
    submit: 'Create workspace',
    submitting: 'Creating your workspace…',
    companyRequired: 'Enter your company name (2-80 characters)',
    nameRequired: 'Enter your full name (2-60 characters)',
    emailInvalid: 'Enter a valid email',
    timezoneInvalid: 'Choose a timezone from the list',
    emailExists: 'An account with this email already exists.',
    rateLimited: 'Too many attempts. Please wait a while and try again.',
    network: 'Network problem. Check your connection and try again.',
    generic: 'We could not complete the setup. Please try again.',
    signInFailed: 'Your workspace is ready, but we could not sign you in. Sign in with the email and password you just chose.',
  },

  onboarding: {
    title: 'Get ConvoyPass ready',
    intro: 'A few steps and your drivers can start submitting passes.',
    progress: (done: number, total: number) => `${done} of ${total} done`,
    dismiss: 'Dismiss',
    dismissLabel: 'Dismiss the setup checklist',
    done: 'Done',
    open: 'Open',
    steps: {
      contractor: { title: 'Add your first contractor', hint: 'The company whose vehicles you let in.' },
      supervisor: { title: 'Add a supervisor for it', hint: 'They approve passes first.' },
      vehicles: { title: 'Add vehicles', hint: 'One by one, or import a CSV.' },
      drivers: { title: 'Add drivers', hint: 'Phone number and a 6-digit PIN.' },
      officer: { title: 'Add an officer', hint: 'They give the final approval.' },
      security: { title: 'Add a security user', hint: 'They check vehicles in at the gate.' },
      settings: { title: 'Review the pass checklist and gates', hint: 'Open Settings to see the defaults.' },
    },
    importCsv: 'Import CSV',
    qrTip: 'Tip: when your vehicles are in, print their QR labels from the QR labels page.',
    qrLink: 'QR labels',
    welcome: 'Welcome to ConvoyPass. Your workspace is ready.',
  },

  account: {
    title: 'Your account',
    name: 'Name',
    role: 'Role',
    contractor: 'Contractor',
    email: 'Email',
    phone: 'Phone',
    changePassword: 'Change password',
    changePin: 'Change PIN',
    current: 'Current password',
    currentPin: 'Current PIN',
    new: 'New password',
    newPin: 'New 6-digit PIN',
    confirm: 'Confirm new password',
    confirmPin: 'Confirm new PIN',
    submit: 'Update password',
    submitPin: 'Update PIN',
    saving: 'Updating…',
    updated: 'Password updated. You stay signed in on this device.',
    updatedPin: 'PIN updated. You stay signed in on this device.',
    currentRequired: 'Enter your current password',
    currentPinRequired: 'Enter your current PIN',
    currentWrong: 'That is not your current password.',
    currentWrongPin: 'That is not your current PIN.',
    sameAsCurrent: 'Choose something different from your current one.',
    tooMany: 'Too many attempts. Please wait a moment and try again.',
    failed: 'Could not update. Please try again.',
  },

  authErrors: {
    invalidCredentials: 'Incorrect details. Please check and try again.',
    accountUnavailable: 'This account is unavailable. Contact your administrator.',
    tooManyAttempts: 'Too many attempts. Please wait a moment and try again.',
    network: 'Network problem. Check your connection and try again.',
    generic: 'Could not sign in. Please try again.',
    accountDisabled: 'Your account has been disabled. Contact your administrator.',
    accountMissing: 'Your account is not set up. Contact your administrator.',
    contractorSuspended: 'Your company account is suspended. Contact your administrator.',
    sessionEnded: 'Your session ended. Please sign in again.',
    recentLoginRequired: 'Please sign in again, then change your password.',
  },

  // Keyed by the `details.reason` returned by Cloud Functions.
  apiErrors: {
    unauthenticated: 'Please sign in again.',
    'caller-not-active': 'Your account cannot perform this action.',
    forbidden: 'You are not allowed to do that.',
    'invalid-input': 'Some details are invalid. Please check and try again.',
    'tenant-mismatch': 'That record belongs to a different organisation.',
    'user-not-found': 'User not found.',
    'contractor-invalid': 'Choose an active contractor.',
    'email-exists': 'That email is already registered.',
    'phone-exists': 'That phone number is already registered.',
    'self-status': 'You cannot disable your own account.',
    'self-reset': 'Use “Change password” for your own account.',
    'recent-login-required': 'Please sign in again, then change your password.',
    'setup-invalid': 'This setup link is invalid or has expired.',
    'weak-password': 'Use at least 10 characters.',
    'common-password': 'That password is too common. Choose another.',
    'password-is-email': 'Your password cannot be your email address.',
    'timezone-invalid': 'Choose a timezone from the list.',
    'plate-exists': 'A vehicle with this plate number already exists.',
    'vehicle-not-found': 'Vehicle not found.',
    'driver-invalid': 'Choose active drivers that belong to this contractor.',
    'contractor-not-found': 'Contractor not found.',
    'photo-path-invalid': 'That photo location is not valid.',
    'not-assigned': "This vehicle isn't assigned to you. Ask your supervisor.",
    'vehicle-suspended': "This vehicle can't be used right now. Contact your supervisor.",
    'contractor-suspended': "This vehicle can't be used right now. Contact your supervisor.",
    'pass-exists': 'A pass for this vehicle was already submitted today.',
    'attempt-mismatch': 'This pass changed while you were filling it in. Reopen the QR code.',
    'attempts-exhausted': 'All attempts are used. Contact your supervisor.',
    'not-resubmitter': 'Only the driver who submitted this pass can fix it.',
    'checklist-invalid': 'The checklist changed. Reopen the QR code to get the latest one.',
    'checklist-note-required': 'Add a short note to every answer marked No.',
    'checklist-blocked': 'An item that must be fixed before the trip is marked No.',
    'evidence-missing': 'A photo did not finish uploading. Retake it and try again.',
    'evidence-invalid': 'A photo could not be accepted. Retake it and try again.',
    'evidence-stale': 'A photo is too old. Retake it and try again.',
    'location-required': 'Your location is required to submit this pass.',
    'pass-not-found': 'That pass no longer exists.',
    'pass-changed': 'This pass changed. Please review it again.',
    'pass-expired': 'This pass is from a previous day and can no longer be decided.',
    'wrong-stage': 'This pass is not at your approval step.',
    'driver-inactive': "This driver's account is disabled, so this pass cannot be decided.",
    'already-checked-in': 'This vehicle is already checked in, so the pass cannot be revoked.',
    has_issues: 'This pass has checklist issues. Open it and review it one by one.',
    'reason-invalid': 'Choose a reason from the list.',
    'note-required': 'Add a short note (at least 3 letters) for this reason.',
    'gate-invalid': 'This gate no longer exists. Choose your gate again.',
    'pass-not-approved': 'This pass is not approved any more. Review it again.',
    'pass-checked-in': 'This vehicle is already checked in.',
    'offline-time-future': "The phone's clock is ahead. Fix the date and time, then try again.",
    'offline-time-stale': 'This offline check-in is more than 12 hours old and was not accepted.',
    'offline-day-mismatch': 'This offline check-in was made on a different day than the pass.',
    'request-conflict': 'This request was already used. Try again.',
    'rate-limited': 'Too many requests. Wait a moment and try again.',
    'device-invalid': 'This device could not be registered for alerts.',
    'range-invalid': 'Choose a valid date range.',
    'range-too-long': 'Choose a range of at most 92 days.',
    'range-too-large': 'This report is too large to run. Narrow the date range or choose a contractor.',
    'id-required': 'Choose a vehicle or a driver first.',
    'filter-invalid': 'That filter is no longer available. Choose another.',
    'reauth-required': 'Please sign in again to continue.',
    'workspace-not-found': 'That workspace no longer exists.',
    'last-admin': 'A workspace must keep at least one active admin. Add another admin first.',
    'invite-not-found': 'That invite no longer exists. Refresh the list.',
    'invite-not-revocable': 'This invite was already used or is being used right now, so it cannot be revoked.',
    'config-missing': 'The app address is not configured on the server (APP_BASE_URL).',
    'signup-disabled': 'Super admin signup is turned off.',
    internal: 'Something went wrong. Please try again.',
  },

  home: {
    welcome: (name: string) => `Hello, ${name}`,
    role: 'Role',
    contractor: 'Contractor',
    placeholder: 'This area is coming soon.',
  },

  vehicle: {
    title: 'Vehicle',
    placeholder: (id: string) => `Vehicle ${id} — details coming soon.`,
    comingSoon: 'Vehicle view coming soon',
  },

  gate: {
    title: 'Gate',
    topBar: 'ConvoyPass gate',
    chooseGate: 'Choose gate',
    gateLabel: (name: string) => `Gate: ${name}`,
    changeGate: 'Change gate',
    pickGateTitle: 'Which gate are you at?',
    pickGateIntro: 'Check-ins and denials are recorded against this gate. It is remembered on this phone.',
    noGateYet: 'Choose your gate before checking vehicles in.',
    online: 'Online',
    offline: 'Offline',
    soundOn: 'Sound on',
    soundOff: 'Sound off',
    queueBadge: (n: number) => `${n} waiting to sync`,
    openQueue: 'Offline queue',
    scan: 'Scan vehicle QR',
    searchLabel: 'Search by plate',
    searchPlaceholder: 'Last digits of the plate, e.g. 4821',
    searchHint: 'Type at least 2 letters or digits.',
    searchNone: 'No vehicle matches that plate.',
    searchLarge: 'Large fleet: searching plates by their start on the server. Type the plate from the beginning.',
    searchFailed: "Couldn't search. Check your connection.",
    tabsLabel: 'Today at the gate',
    tabs: { awaiting: 'Awaiting entry', checkedIn: 'Checked in' },
    emptyAwaiting: 'No approved vehicles waiting',
    emptyAwaitingBody: 'Vehicles appear here once an officer approves today’s pass.',
    emptyCheckedIn: 'Nobody checked in yet today',
    emptyCheckedInBody: 'Vehicles you check in today are listed here.',
    listFailed: "Couldn't load today's passes. Check your connection.",
    capNotice: 'Showing the first 300 passes for today.',
    approvedAt: (time: string) => `Approved ${time}`,
    checkedInAt: (time: string, gate: string) => `In ${time} · ${gate}`,
    pendingSync: 'Pending sync',
    lastSynced: (time: string) => `Last synced ${time}`,
    notSyncedYet: 'Not synced yet',
    offlineBanner: 'Offline: showing saved data. Check-ins will sync when the connection returns.',
    staleBanner: 'Connection is slow: data may be out of date.',
    failedBanner: (n: number) => `${n} offline ${n === 1 ? 'check-in was' : 'items were'} rejected. Open queue.`,
    chip: { approved: 'Approved', checked_in: 'Checked in', none: 'Not approved' },
    signOutPending: (n: number) => `${n} offline ${n === 1 ? 'item has' : 'items have'} not synced yet. They stay on this phone and sync the next time you sign in. Sign out anyway?`,
    signOutTitle: 'Sign out?',
    // Vehicle view
    back: 'Back',
    banner: {
      approved: 'APPROVED',
      already_checked_in: 'ALREADY CHECKED IN',
      not_approved: 'NOT APPROVED',
      loading: 'Checking…',
    },
    reason: {
      pending_supervisor: 'Waiting for the supervisor to approve.',
      pending_officer: 'Waiting for the officer to approve.',
      rejected: (reason: string) => `Pass rejected: ${reason}`,
      rejectedNoReason: 'The pass was rejected.',
      no_pass_today: 'No pass submitted for today.',
      vehicle_suspended: 'This vehicle is suspended.',
      driver_suspended: 'The driver on this pass is disabled.',
      contractor_suspended: 'This contractor is suspended.',
      not_found: 'Unknown QR code. This vehicle is not registered here.',
    },
    alreadyBy: (time: string, name: string, gate: string) => `Checked in at ${time} by ${name} · ${gate}`,
    pendingSyncBody: 'Checked in on this phone while offline. Waiting to sync.',
    plate: 'Plate',
    vehicleType: 'Type',
    contractor: 'Contractor',
    driver: 'Driver',
    noDriver: 'No driver on a pass today',
    noPhoto: 'No photo on file',
    photoOffline: 'Photo not available offline',
    enlargePhoto: (name: string) => `Enlarge photo of ${name}`,
    photoOf: (name: string) => `Photo of ${name}`,
    closePhoto: 'Close photo',
    approvedBy: 'Approved by',
    supervisorLine: (name: string, time: string) => `Supervisor: ${name} · ${time}`,
    officerLine: (name: string, time: string) => `Officer: ${name} · ${time}`,
    offlineStrip: 'Offline: data may be out of date. Check-in will sync later.',
    checkIn: 'CHECK IN',
    checkInOffline: 'Check in (will sync)',
    checkingIn: 'Checking in…',
    denyLink: 'Deny entry',
    recordDenied: 'Record denied entry',
    scanNext: 'Scan next',
    readOnly: 'Read only: only security can check vehicles in.',
    loadFailed: "Couldn't load this vehicle.",
    // Success
    successTitle: 'CHECKED IN',
    savedOffline: 'Saved offline, will sync',
    deviceTime: 'device time',
    successBy: (name: string) => `By ${name}`,
    successGate: (gate: string) => `Gate: ${gate}`,
    nextIn: (n: number) => `Scanning next in ${n}…`,
    homeIn: (n: number) => `Back to the list in ${n}…`,
    stay: 'Tap to stay on this screen',
    stayed: 'Staying on this screen',
    continue: 'Continue',
    // Errors after a check-in attempt
    alreadyCheckedIn: (time: string, name: string) => `Already checked in at ${time} by ${name}`,
    queueFull: 'The offline queue is full (50). Get back online to sync before checking in more vehicles.',
    // Deny
    denyTitle: 'Deny entry',
    denyIntro: 'This is logged for the officers. It does not change the pass.',
    denyReason: 'Reason',
    denyNoteOptional: 'Note (optional)',
    denyNoteRequired: 'Note (required for this reason)',
    denyNoteError: 'Add a short note (at least 3 letters).',
    denyPick: 'Choose a reason.',
    denyConfirm: 'Record denial',
    denied: (plate: string) => `Entry denied for ${plate}. Logged.`,
    deniedOffline: (plate: string) => `Entry denied for ${plate}. Saved offline, will sync.`,
    // Scanner
    scanner: {
      title: 'Scan vehicle QR',
      hint: 'Point the camera at the QR label on the vehicle.',
      close: 'Close scanner',
      torchOn: 'Torch on',
      torchOff: 'Torch off',
      starting: 'Starting camera…',
      notOurs: 'Not a ConvoyPass QR code',
      deniedTitle: 'Camera blocked',
      deniedBody: 'Allow camera access for this site: tap the lock or camera icon in the address bar, allow the camera, then try again. You can also search by plate.',
      noCamera: 'No camera found on this device. Search by plate instead.',
      failed: "Couldn't start the camera. Close the scanner and try again.",
      insecure: 'The camera needs a secure (https) connection.',
      retry: 'Try again',
    },
    // Queue
    queue: {
      title: 'Offline queue',
      intro: 'Check-ins and denials made while offline. They sync automatically, oldest first.',
      empty: 'Nothing waiting',
      emptyBody: 'Everything has synced.',
      checkIn: 'Check-in',
      deny: 'Denied entry',
      waiting: 'Waiting',
      failed: 'Rejected',
      captured: (time: string) => `Captured ${time} (device time)`,
      retry: 'Retry now',
      dismiss: 'Dismiss',
      syncing: 'Syncing…',
      back: 'Back to gate',
    },
    wakeLock: 'Screen stays on while this page is open.',
  },

  pass: {
    gate: {
      checking: 'Checking this vehicle…',
      loadFailed: "Couldn't check this vehicle.",
      offline: "You're offline. Reconnect and try again.",
      retry: 'Try again',
      notAssignedTitle: 'Not your vehicle',
      notAssigned: "This vehicle isn't assigned to you. Ask your supervisor.",
      suspendedTitle: 'Vehicle unavailable',
      suspended: "This vehicle can't be used right now. Contact your supervisor.",
      notFoundTitle: 'Unknown QR code',
      notFound: 'Unknown QR code.',
      lockedTitle: 'Pass was rejected',
      lockedOther: (name: string) => `${name} must fix and resubmit this pass.`,
      lockedMax: 'All attempts are used. Contact your supervisor.',
      rejectedTitle: 'Pass rejected',
      rejectedReason: 'Reason',
      fixAndResubmit: 'Fix and resubmit',
      attemptOf: (n: number) => `Attempt ${n}`,
      home: 'Back to home',
    },
    status: {
      pendingTitle: 'Pass submitted',
      pendingBody: (plate: string) => `${plate} is waiting for approval.`,
      approvedTitle: 'Approved',
      approvedBody: 'Drive to the gate and show this screen.',
      checkedInTitle: 'Checked in',
      checkedInBody: 'This vehicle has been checked in at the gate.',
      submittedBy: (name: string) => `Submitted by ${name}`,
      submittedAt: (when: string) => `at ${when}`,
      rejectedLive: 'This pass was rejected. Open the QR code again to fix it.',
      steps: { submitted: 'Submitted', supervisor: 'Supervisor', officer: 'Officer', gate: 'Gate' },
      timeline: 'Approval progress',
      done: 'Done',
      reopen: 'Open again',
    },
    form: {
      title: 'Pre-trip check',
      driver: 'Driver',
      today: 'Today',
      reasonBanner: 'Rejected: fix and resubmit',
      photosTitle: 'Photos',
      gps: 'GPS device photo',
      gpsHint: 'Show the GPS unit clearly.',
      dashcam: 'Dashcam photo',
      dashcamHint: 'Show the dashcam and its screen.',
      takePhoto: 'Take photo',
      retake: 'Retake',
      remove: 'Remove',
      retryUpload: 'Retry upload',
      uploading: 'Uploading…',
      uploaded: 'Uploaded',
      uploadFailed: 'Upload failed',
      checklistTitle: 'Checklist',
      allOk: 'All OK',
      yes: 'Yes',
      no: 'No',
      noteLabel: 'What is wrong?',
      notePlaceholder: 'Short note (at least 3 letters)',
      noteWarning: 'Your supervisor will see this.',
      failBlocks: 'This must be fixed before the trip. You cannot submit with this marked No.',
      extraTitle: 'Extra photos',
      extraHint: 'Optional. Add a photo if something needs showing.',
      addExtra: 'Add photo',
      extraN: (n: number) => `Extra photo ${n}`,
      progress: (done: number, total: number) => `${done} of ${total} done`,
      submit: 'Submit',
      submitting: 'Submitting…',
      needPhotos: 'Add both required photos to continue.',
      waitingUploads: 'Waiting for photos to finish uploading…',
      locationNote: 'Your location is saved with this pass to confirm where the check was done.',
      locationWaiting: 'Getting your location…',
      locationFailed: 'We could not get your location. Turn on location for this site and try again.',
      locationRetry: 'Try location again',
      submitted: 'Pass submitted',
      stalePhotos: 'Re-uploading photos…',
    },
    camera: {
      title: (label: string) => label,
      capture: 'Capture',
      close: 'Close camera',
      starting: 'Starting camera…',
      denied: 'Camera access was blocked. Allow the camera for this site, or choose a photo instead.',
      unsupported: "This browser can't open the camera here. Take or choose a photo instead.",
      chooseFile: 'Take or choose photo',
      processing: 'Preparing photo…',
      failed: 'Could not use that photo. Try again.',
    },
  },

  driverHome: {
    howTitle: 'How it works',
    howBody: 'Scan the QR on your vehicle with your phone camera.',
    vehiclesTitle: 'My vehicles today',
    vehiclesEmpty: 'No vehicles are assigned to you yet. Ask your supervisor.',
    recentTitle: 'Recent passes',
    recentEmpty: 'Your passes will show up here.',
    noPassToday: 'No pass from you today',
    fixNow: 'Tap to fix and resubmit',
    fixAndResubmit: 'Fix and resubmit',
    rejectedReason: 'Reason',
    rejectedBy: (name: string) => `Rejected by ${name}`,
    approvedTitle: 'Approved',
    approvedBody: 'Drive to the gate and show your pass.',
    loadFailed: "Couldn't load your vehicles.",
    attempt: (n: number) => `Attempt ${n}`,
    chips: {
      none: 'No pass from you today',
      submitted: 'Submitted',
      supervisor_approved: 'Supervisor approved',
      officer_approved: 'Approved',
      checked_in: 'Checked in',
      rejected: 'Rejected',
    },
  },

  approvals: {
    status: {
      submitted: 'Pending supervisor',
      supervisor_approved: 'Awaiting officer',
      officer_approved: 'Approved',
      checked_in: 'Checked in',
      rejected: 'Rejected',
      expired: 'Expired',
    },
    time: {
      justNow: 'Just now',
      minutes: (n: number) => `${n} min ago`,
      hours: (n: number) => `${n} h ago`,
      days: (n: number) => `${n} d ago`,
    },
    card: {
      issues: (n: number) => `${n} ${n === 1 ? 'issue' : 'issues'}`,
      openToReview: 'Open to review',
      select: (plate: string) => `Select ${plate}`,
      attempt: (n: number) => `Attempt ${n}`,
      photoOf: (what: string, plate: string) => `${what} photo of ${plate}`,
    },
    evidence: {
      title: 'Photos',
      gps: 'GPS device',
      dashcam: 'Dashcam',
      extra: (n: number) => `Extra photo ${n}`,
      open: (what: string) => `Open ${what} photo`,
      close: 'Close photos',
      previous: 'Previous photo',
      next: 'Next photo',
      hint: 'Double-tap or double-click to zoom. Swipe or use the arrow keys to move between photos.',
      loadFailed: "Couldn't load this photo.",
      retry: 'Try again',
      position: (i: number, n: number) => `${i} of ${n}`,
      zoomStamp: 'Zoom to stamp',
      stampHint: 'The plate and capture time are printed in the bottom-left corner of each photo.',
    },
    checklist: {
      title: 'Checklist',
      allYes: 'All answers are Yes',
      yes: 'Yes',
      no: 'No',
      driverNote: (note: string) => `Driver's note: ${note}`,
    },
    info: {
      vehicleHistory: 'Vehicle history',
      driver: 'Driver',
      vehicle: 'Vehicle',
      contractor: 'Contractor',
      submitted: 'Submitted',
      attempt: 'Attempt',
      supervisorApproved: 'Supervisor approved',
      officerApproved: 'Officer approved',
      by: (name: string) => `by ${name}`,
      previousRejection: 'Earlier rejection',
      reason: 'Reason',
      stage: { supervisor: 'Supervisor', officer: 'Officer', revoked: 'Revoked', gate: 'Gate' },
    },
    timeline: { title: 'Progress', waiting: 'Waiting' },
    reject: {
      rejectTitle: 'Reject this pass',
      revokeTitle: 'Revoke this approval',
      rejectIntro: 'The driver sees the reason and can fix and resubmit.',
      revokeIntro: 'The approval is cancelled and the driver must fix and resubmit.',
      reasonLegend: 'Reason',
      noteLabel: 'Note',
      noteOptional: 'Note for the driver (optional)',
      noteRequired: 'Note (required for this reason)',
      notePlaceholder: 'What should the driver fix?',
      noteError: 'Add a short note (at least 3 letters).',
      pickReason: 'Choose a reason.',
      confirmReject: 'Reject pass',
      confirmRevoke: 'Revoke approval',
      reasonsLoadFailed: "Couldn't load the reasons list.",
    },
    decision: {
      approve: 'Approve',
      reject: 'Reject',
      issuesWarning: 'This pass has checklist issues. Look at the answers marked No before approving.',
      expired: 'This pass is from a previous day. It cannot be approved or rejected.',
      changedTitle: 'This pass changed. Please review it again.',
      changedBody: 'The driver or another reviewer updated it. Check the photos and answers before you decide.',
      reviewAgain: 'Review again',
      gone: 'This pass is no longer waiting for you.',
      notFound: 'This pass could not be found.',
      loadFailed: "Couldn't load this pass.",
    },
    toast: {
      approved: (plate: string) => `${plate} approved`,
      rejected: (plate: string) => `${plate} rejected`,
      revoked: (plate: string) => `${plate} approval revoked`,
      changed: 'This pass changed. Please review it again.',
    },
    bulk: {
      approveN: (n: number) => `Approve ${n}`,
      select: 'Select',
      done: 'Done',
      selectedCount: (n: number) => `${n} selected`,
      clear: 'Clear',
      confirmTitle: (n: number) => `Approve ${n} ${n === 1 ? 'pass' : 'passes'}?`,
      confirmBody: 'Each pass is checked again on the server. Passes with a No answer are never approved in bulk.',
      resultsTitle: 'Bulk approval result',
      resultsSummary: (ok: number, failed: number) => (failed === 0 ? `${ok} approved.` : `${ok} approved, ${failed} not approved.`),
      failedHeading: 'Not approved',
      close: 'Close',
      itemError: {
        has_issues: 'Has checklist issues. Open it to review.',
        'pass-changed': 'Changed since you loaded it. Review it again.',
        'pass-expired': 'From a previous day.',
        'pass-not-found': 'No longer exists.',
        forbidden: 'Not allowed.',
        'tenant-mismatch': 'Not allowed.',
        'vehicle-suspended': 'The vehicle is suspended.',
        'contractor-suspended': 'The contractor is suspended.',
        'driver-inactive': 'The driver is disabled.',
        internal: 'Something went wrong.',
      },
    },
    queue: { loadFailed: "Couldn't load passes. Check your connection.", capNotice: 'Showing the latest 100. Older passes are not listed.' },
  },

  list: {
    count: (shown: number, total: number) => (shown === total ? `${total}` : `${shown} of ${total}`),
    capNotice: (n: number) => `Showing the first ${n} records. Narrow the list with search or filters.`,
    allStatuses: 'All statuses',
    allContractors: 'All contractors',
    noMatchTitle: 'Nothing matches',
    noMatchBody: 'Try a different search or clear the filters.',
    clearFilters: 'Clear filters',
    showMore: (n: number) => `Show more (${n})`,
  },

  vehicles: {
    title: 'Vehicles',
    add: 'Add vehicle',
    edit: 'Edit vehicle',
    searchPlaceholder: 'Search plate, make or driver',
    searchLabel: 'Search vehicles',
    emptyTitle: 'No vehicles yet',
    emptyBody: 'Add a vehicle to generate its permanent QR code.',
    columns: { plate: 'Plate', type: 'Type', contractor: 'Contractor', drivers: 'Drivers', status: 'Status' },
    noDrivers: 'No drivers assigned',
    form: {
      plate: 'Plate number',
      plateHint: 'e.g. WP LJ-4821, NP KA 1234, CAB-1234',
      saveAs: 'Will be saved as',
      type: 'Vehicle type',
      typePlaceholder: 'Select a type',
      makeModel: 'Make and model',
      contractor: 'Contractor',
      contractorPlaceholder: 'Select a contractor',
      drivers: 'Assigned drivers',
      driversEmpty: 'No active drivers for this contractor yet.',
      driversPickContractor: 'Select a contractor to choose drivers.',
      submit: 'Create vehicle',
      created: 'Vehicle created',
      updated: 'Vehicle updated',
    },
    errors: {
      plate: 'Enter 4 to 12 letters or numbers',
      type: 'Choose a vehicle type',
      makeModel: 'Keep make and model under 60 characters',
      contractor: 'Select a contractor',
      duplicateInFile: 'Duplicate plate in this file',
    },
    drawer: {
      qrTitle: 'Vehicle QR',
      downloadPng: 'Download PNG',
      downloadSvg: 'Download SVG',
      copyLink: 'Copy link',
      linkCopied: 'Link copied',
      print: 'Print label',
      drivers: 'Assigned drivers',
      editDrivers: 'Edit drivers',
      saveDrivers: 'Save drivers',
      driversSaved: 'Drivers updated',
      suspend: 'Suspend vehicle',
      activate: 'Activate vehicle',
      suspendTitle: 'Suspend this vehicle?',
      activateTitle: 'Activate this vehicle?',
      suspendBody: (plate: string) => `${plate} will be marked suspended. Its QR code stays valid, but it cannot be used for new passes.`,
      activateBody: (plate: string) => `${plate} will be active again.`,
      suspended: 'Vehicle suspended',
      activated: 'Vehicle activated',
      permanentId: 'QR ID',
    },
    import: {
      button: 'Import CSV',
      title: 'Import vehicles',
      template: 'Download template',
      pickContractor: 'Select the contractor these vehicles belong to.',
      chooseFile: 'Choose a CSV file',
      hint: 'Columns: plateNo, type, makeModel. Up to 2000 rows.',
      parsing: 'Reading file…',
      fileEmpty: 'No rows found in this file.',
      headerError: 'The file needs plateNo and type columns.',
      tooMany: (n: number) => `Only the first ${n} rows are used.`,
      previewTitle: 'Preview',
      valid: (n: number) => `${n} valid`,
      invalid: (n: number) => `${n} with errors`,
      rowCol: 'Row',
      statusCol: 'Result',
      ok: 'Ready',
      importValid: (n: number) => `Import ${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
      importing: 'Importing…',
      nothingValid: 'There are no valid rows to import.',
      summaryTitle: 'Import finished',
      imported: (n: number) => `${n} imported`,
      failed: (n: number) => `${n} failed`,
      downloadFailed: 'Download failed rows',
      another: 'Import another file',
      rowErrors: {
        'invalid-plate': 'Invalid plate number',
        'invalid-type': 'Unknown vehicle type',
        'invalid-make-model': 'Make and model too long',
        'plate-exists': 'Plate already exists',
        internal: 'Could not save this row',
      },
    },
  },

  drivers: {
    title: 'Drivers',
    add: 'Add driver',
    edit: 'Edit driver',
    searchPlaceholder: 'Search name, phone or vehicle',
    searchLabel: 'Search drivers',
    emptyTitle: 'No drivers yet',
    emptyBody: 'Add a driver so they can be assigned to vehicles.',
    columns: { driver: 'Driver', phone: 'Phone', vehicles: 'Vehicles', status: 'Status' },
    noVehicles: 'No vehicles assigned',
    form: {
      name: 'Full name',
      phone: 'Mobile number',
      contractor: 'Contractor',
      contractorPlaceholder: 'Select a contractor',
      licenseNo: 'Licence number',
      pin: 'Temporary 6-digit PIN',
      generate: 'Generate',
      photo: 'Photo',
      takePhoto: 'Take or choose photo',
      changePhoto: 'Change photo',
      removeSelected: 'Remove',
      photoHint: 'Optional. Resized and compressed before upload.',
      photoFailed: 'Could not use that photo. Try another one.',
      nameRequired: 'Enter a name',
      contractorRequired: 'Select a contractor',
      pinTrivial: 'Choose a PIN that is harder to guess',
      submit: 'Create driver',
      created: 'Driver created',
      updated: 'Driver updated',
      photoUploadFailed: 'Driver saved, but the photo could not be uploaded. Edit the driver to try again.',
    },
    credentials: {
      title: 'Share sign-in details',
      warning: 'This is the only time the PIN is shown. The driver must change it on first sign-in.',
      phone: 'Phone',
      pin: 'PIN',
      copy: 'Copy details',
      copied: 'Details copied',
      whatsapp: 'Share on WhatsApp',
      message: (appUrl: string, phone: string, pin: string) =>
        `Welcome to ConvoyPass.\nSign in at ${appUrl}\nPhone: ${phone}\nPIN: ${pin}\nYou must change your PIN the first time you sign in.`,
      copyText: (appUrl: string, phone: string, pin: string) =>
        `ConvoyPass\n${appUrl}\nPhone: ${phone}\nPIN: ${pin}`,
    },
    resetPin: 'Reset PIN',
    disable: 'Disable',
    enable: 'Enable',
    disableTitle: 'Disable this driver?',
    enableTitle: 'Enable this driver?',
    disableBody: (name: string) => `${name} will be signed out and cannot sign in. They are also removed from new vehicle assignments.`,
    enableBody: (name: string) => `${name} will be able to sign in again.`,
    disabled: 'Driver disabled',
    enabled: 'Driver enabled',
    photoAlt: (name: string) => `Photo of ${name}`,
  },

  qr: {
    title: 'QR labels',
    devBanner: 'Dev link: do not print',
    devBannerBody: (url: string) => `QR codes currently point to ${url}. Labels printed now will not work in production.`,
    missingBase: 'VITE_APP_BASE_URL is not set, so QR codes cannot be generated.',
    missingBaseBody: 'Set VITE_APP_BASE_URL in the web app environment (see .env.example) and rebuild.',
    selection: 'Vehicles',
    selectAll: 'All vehicles',
    selectContractor: 'By contractor',
    selectManual: 'Pick vehicles',
    contractor: 'Contractor',
    size: 'Label size',
    sizeLarge: 'Large (90 mm, 6 per page)',
    sizeSmall: 'Small (50 mm, 15 per page)',
    print: 'Print',
    selected: (n: number) => `${n} selected`,
    labelCount: (n: number) => `${n} ${n === 1 ? 'label' : 'labels'}`,
    noneSelected: 'Select at least one vehicle to print.',
    preview: 'Preview',
    activeOnly: 'Suspended vehicles are not included unless picked by hand.',
    selectVisible: 'Select all shown',
    clearSelection: 'Clear',
    brand: 'ConvoyPass',
  },

  supervisor: {
    nav: { home: 'Home', approvals: 'Approvals', vehicles: 'Vehicles', drivers: 'Drivers', qr: 'QR' },
    mainNav: 'Main navigation',
    approvals: {
      title: 'Approvals',
      tabsLabel: 'Pass lists',
      tabs: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' },
      pendingEmptyTitle: 'All caught up',
      pendingEmptyBody: 'New passes appear here as soon as drivers submit them.',
      approvedEmptyTitle: 'Nothing approved yet today',
      approvedEmptyBody: 'Passes you approve today are listed here.',
      rejectedEmptyTitle: 'Nothing rejected today',
      rejectedEmptyBody: 'Passes rejected today, by you or the officer, are listed here.',
      review: {
        title: 'Review pass',
        back: 'Back to approvals',
        position: (i: number, n: number) => `${i} of ${n} waiting`,
        alreadyDecided: 'This pass has already been decided.',
      },
    },
    homePending: (n: number) => (n === 0 ? 'Nothing is waiting for you' : `${n} ${n === 1 ? 'pass is' : 'passes are'} waiting for you`),
    homePendingTitle: 'Waiting for approval',
    openApprovals: 'Open approvals',
    vehicles: 'Vehicles',
    drivers: 'Drivers',
    quickActions: 'Quick actions',
    approvalsTitle: 'Approvals',
    noContractor: 'Your account is not linked to a contractor. Contact your administrator.',
  },

  dashboard: {
    title: 'Dashboard',
    intro: 'Today across all contractors. Live.',
    navOverview: 'Overview',
    updated: (time: string) => `Updated ${time}`,
    live: 'Live',
    offline: 'Reconnecting…',
    capNotice: (n: number) => `Showing the first ${n} passes of today. Numbers below may be incomplete.`,
    loadFailed: 'Could not load today’s passes.',
    kpis: {
      title: 'Today',
      submitted: 'Submitted today',
      waitingSupervisor: 'Waiting supervisor',
      waitingOfficer: 'Waiting officer',
      approved: 'Approved (awaiting entry)',
      checkedIn: 'Checked in today',
      rejected: 'Rejected today',
    },
    attention: {
      title: 'Needs attention',
      nothing: 'Nothing needs attention',
      nothingHint: 'No pass is past its time target and nobody was turned away today.',
      overdue: 'Past time target',
      heldBy: 'Held by',
      supervisorsOf: (contractor: string) => `Supervisors of ${contractor}`,
      officers: 'Officers',
      age: 'Waiting',
      deniedToday: (n: number) => (n === 1 ? '1 entry denied today' : `${n} entries denied today`),
      viewDenied: 'Open the gate log',
      open: 'Open',
      columns: { age: 'Waiting', contractor: 'Contractor', plate: 'Plate', holder: 'Held by' },
      overBy: (minutes: number) => `${minutes} min over`,
    },
    contractors: {
      title: 'Contractors today',
      empty: 'No passes submitted today',
      emptyHint: 'Contractors appear here as soon as a driver submits a pass.',
      columns: { contractor: 'Contractor', submitted: 'Submitted', waiting: 'Waiting', approved: 'Approved', checkedIn: 'Checked in', rejected: 'Rejected' },
    },
    trend: {
      title: 'Trend',
      range: (days: number) => `Last ${days} days`,
      daysLabel: 'Period',
      refresh: 'Refresh',
      viewTable: 'View as table',
      viewChart: 'View as chart',
      updated: (time: string) => `Fetched ${time}`,
      loadFailed: 'Could not load the trend.',
      empty: 'No passes in this period',
      series: { submitted: 'Submitted', checkedIn: 'Checked in', rejected: 'Rejected' },
      day: 'Day',
      chartLabel: (days: number) => `Chart: submitted, checked in and rejected passes per day over the last ${days} days. A table version is available.`,
    },
    recent: {
      title: 'Recent gate activity',
      empty: 'Nobody has been checked in or turned away yet today',
      checkIn: 'Check-in',
      denied: 'Denied',
      unverified: 'offline, device time unverified',
    },
  },

  reports: {
    title: 'Reports',
    intro: 'Read only. Pick a report, set the filters and press Apply.',
    pickerLabel: 'Report',
    types: {
      gate_log: { title: 'Gate log', description: 'Every check-in and denied entry, oldest first.' },
      contractor_activity: { title: 'Contractor activity', description: 'Submissions, approvals, check-ins and rejection rate per contractor.' },
      turnaround: { title: 'Turnaround times', description: 'Median and p90 minutes at each approval stage, and per approver.' },
      rejections: { title: 'Rejections', description: 'Every rejection with its reason, stage and approver.' },
      vehicle_history: { title: 'Vehicle history', description: 'One row per day for a single vehicle.' },
      driver_history: { title: 'Driver history', description: 'One row per day for a single driver.' },
    },
    filters: {
      title: 'Filters',
      range: 'Date range',
      from: 'From',
      to: 'To',
      contractor: 'Contractor',
      allContractors: 'All contractors',
      vehicle: 'Vehicle',
      driver: 'Driver',
      vehiclePlaceholder: 'Search by plate',
      driverPlaceholder: 'Search by name',
      noMatches: 'No matches',
      clear: 'Clear',
      apply: 'Apply',
      maxRange: 'Choose at most 92 days.',
      orderError: '“From” must not be after “To”.',
      needVehicle: 'Choose a vehicle to run this report.',
      needDriver: 'Choose a driver to run this report.',
      presets: { today: 'Today', yesterday: 'Yesterday', last7: 'Last 7 days', last30: 'Last 30 days', thisMonth: 'This month', custom: 'Custom' },
    },
    idle: 'Choose filters and press Apply to run the report.',
    running: 'Running report…',
    runFailed: 'Could not run the report.',
    empty: 'No data for these filters',
    emptyHint: 'Try a wider date range or remove a filter.',
    generated: (time: string) => `Generated ${time}`,
    range: (from: string, to: string) => (from === to ? from : `${from} to ${to}`),
    summary: 'Summary',
    data: 'Data',
    table: { rows: (n: number) => (n === 1 ? '1 row' : `${n} rows`), page: (page: number, pages: number) => `Page ${page} of ${pages}`, previous: 'Previous', next: 'Next', sortBy: (label: string) => `Sort by ${label}` },
    toolbar: { csv: 'Export CSV', xlsx: 'Export XLSX', print: 'Print / Save as PDF', exporting: 'Preparing…', exportFailed: 'Could not create the file.' },
    chart: { show: 'View as chart', table: 'View as table', unavailable: 'The chart could not load. The table below has the same numbers.' },
    xlsx: { report: 'Report', range: 'Range', filters: 'Filters', generated: 'Generated', timezone: 'Time zone', none: 'None', keyFigures: 'Key figures' },
    forbidden: 'Reports are for admins and officers.',
    contractorChart: { submissions: 'Submissions', checkedIn: 'Checked in', rejections: 'Rejections' },
  },

  officer: {
    title: 'Pass approvals',
    topBar: 'ConvoyPass officer',
    nav: { queue: 'Approvals', overview: 'Overview', reports: 'Reports' },
    tabsLabel: 'Pass lists',
    tabs: { awaiting: 'Awaiting me', approved: 'Approved today', rejected: 'Rejected today', expired: 'Expired' },
    contractor: 'Contractor',
    allContractors: 'All contractors',
    columns: {
      select: 'Select',
      plate: 'Plate',
      contractor: 'Contractor',
      driver: 'Driver',
      submitted: 'Submitted',
      supervisor: 'Supervisor',
      issues: 'Issues',
      photos: 'Photos',
      actions: 'Actions',
      status: 'Status',
    },
    approveSelected: (n: number) => `Approve selected (${n})`,
    selectAll: 'Select all passes without issues',
    selectRow: (plate: string) => `Select ${plate}`,
    noIssues: '—',
    review: 'Review',
    revoke: 'Revoke',
    emptyAwaiting: 'Nothing awaiting you',
    emptyAwaitingBody: 'Passes appear here once a supervisor approves them.',
    emptyApproved: 'Nothing approved today',
    emptyApprovedBody: 'Passes you approve today are listed here.',
    emptyRejected: 'Nothing rejected today',
    emptyRejectedBody: 'Passes rejected today are listed here.',
    emptyExpired: 'No expired passes',
    emptyExpiredBody: 'Passes still waiting from a previous day show here, read only.',
    expiredNote: 'These passes are from a previous day and cannot be approved or rejected any more.',
    noMatch: 'No passes for this contractor.',
    panel: {
      title: 'Review pass',
      close: 'Close review panel',
      previous: 'Previous pass',
      next: 'Next pass',
      position: (i: number, n: number) => `${i} of ${n}`,
      shortcuts: 'Shortcuts',
      shortcutsHint: 'J next · K previous · A approve · R reject · Esc close',
      readOnly: 'This pass is read only.',
    },
    revokeNote: 'Revoke is available until the vehicle checks in.',
  },

  errorPages: {
    forbiddenTitle: '403 — Access denied',
    forbiddenBody: 'You do not have permission to view this page.',
    notFoundTitle: '404 — Page not found',
    notFoundBody: 'The page you are looking for does not exist.',
    goHome: 'Go to my home',
    signInRequired: 'Go to sign in',
  },

  admin: {
    nav: { dashboard: 'Dashboard', reports: 'Reports', users: 'Users', contractors: 'Contractors', vehicles: 'Vehicles', drivers: 'Drivers', passes: 'Passes', qr: 'QR labels', settings: 'Settings' },
    gates: {
      title: 'Gates',
      hint: 'Security picks one of these on their phone. 1 to 10 gates.',
      name: 'Gate name',
      add: 'Add gate',
      remove: 'Remove',
      nameError: 'Use 2 to 40 characters',
      min: 'Keep at least one gate.',
      max: 'You can have at most 10 gates.',
      usingDefaults: 'Showing the default gate. Save to make it your own.',
    },
    sla: {
      title: 'Review time targets (SLA)',
      hint: 'A pass waiting longer than this appears in the dashboard attention panel. 5 to 240 minutes.',
      supervisor: 'Supervisor, minutes',
      officer: 'Officer, minutes',
      error: 'Use a whole number from 5 to 240',
      usingDefaults: 'Showing the default (30 minutes each). Save to make it your own.',
    },
    panel: 'Admin',
    passes: {
      title: 'Passes',
      intro: 'Every pass in your organisation. Reviewers approve and reject; you can view everything and revoke an approval.',
      date: 'Date',
      status: 'Status',
      contractor: 'Contractor',
      allStatuses: 'All statuses',
      allContractors: 'All contractors',
      columns: { plate: 'Plate', contractor: 'Contractor', driver: 'Driver', status: 'Status', submitted: 'Submitted', issues: 'Issues' },
      emptyTitle: 'No passes match',
      emptyBody: 'Try another date, status or contractor.',
      loadFailed: "Couldn't load passes.",
      count: (n: number) => `${n} ${n === 1 ? 'pass' : 'passes'}`,
      open: (plate: string) => `Open ${plate}`,
      drawerTitle: 'Pass details',
      revoke: 'Revoke approval',
      revokeHint: 'Available while the pass is approved and the vehicle has not checked in.',
      historyTitle: 'History',
      historyEmpty: 'No decisions have been made yet.',
      checkInTitle: 'Gate check-in',
      checkInLine: (name: string, time: string, gate: string) => `${name} · ${time} · ${gate}`,
      checkInOffline: (time: string) => `Captured offline at ${time} (device time, unverified)`,
      attemptN: (n: number) => `Attempt ${n}`,
      day: 'Day',
      pickDay: 'Pick a date',
    },
    reasons: {
      title: 'Rejection reasons',
      hint: 'Reviewers pick one of these when they reject or revoke a pass. 2 to 10 reasons. “Other” always exists and needs a note.',
      label: 'Reason',
      add: 'Add reason',
      remove: 'Remove',
      moveUp: 'Move up',
      moveDown: 'Move down',
      locked: 'Always available',
      lockedLabel: 'Locked',
      labelError: 'Use 3 to 60 characters',
      min: 'Keep at least 2 reasons.',
      max: 'You can have at most 10 reasons.',
      usingDefaults: 'Showing the default reasons. Save to make them your own.',
      newReason: 'New reason',
    },
    settings: {
      adminsTitle: 'Admins',
      adminsHint: 'Read only. Admin accounts are managed by ConvoyPass.',
      adminsNote: 'To add or reset an admin, contact your ConvoyPass administrator.',
      adminsEmpty: 'No admins found.',
      adminsLoadFailed: 'Could not load the admins.',
      title: 'Pass settings',
      intro: 'Drivers see these changes the next time they open a vehicle.',
      checklistTitle: 'Pre-trip checklist',
      checklistHint: 'Every item is a required answer. Up to 12 items.',
      label: 'Question',
      blocks: 'Blocks submission',
      blocksHint: 'A No answer stops the driver from submitting.',
      add: 'Add item',
      remove: 'Remove',
      moveUp: 'Move up',
      moveDown: 'Move down',
      labelError: 'Use 3 to 60 characters',
      needOne: 'Keep at least one checklist item.',
      max: 'You can have at most 12 items.',
      requireLocation: 'Require location',
      requireLocationHint: 'Drivers must share their location to submit.',
      maxExtra: 'Extra photos allowed',
      timezone: 'Timezone',
      timezoneHint: 'A day (and so “one pass per vehicle per day”) follows this timezone.',
      save: 'Save settings',
      saved: 'Settings saved',
      usingDefaults: 'Showing the default checklist. Save to make it your own.',
      loadFailed: "Couldn't load settings.",
      newItem: 'New item',
    },
    users: {
      title: 'Users',
      create: 'Create user',
      searchPlaceholder: 'Search name, email or phone',
      searchLabel: 'Search users',
      roleFilter: 'Role',
      statusFilter: 'Status',
      emptyTitle: 'No users found',
      emptyBody: 'Try changing the filters, or create a user.',
      columns: { name: 'Name', role: 'Role', login: 'Email / phone', contractor: 'Contractor', status: 'Status' },
      mustChange: 'Must change password',
      managedBy: 'Managed by ConvoyPass',
      adminNote: 'To add or reset an admin, contact your ConvoyPass administrator.',
      count: (n: number) => `${n} ${n === 1 ? 'user' : 'users'}`,
    },
    createUser: {
      title: 'Create user',
      role: 'Role',
      name: 'Full name',
      email: 'Email',
      phone: 'Phone number',
      contractor: 'Contractor',
      contractorPlaceholder: 'Select a contractor',
      noContractors: 'Create an active contractor first.',
      password: 'Temporary password',
      pin: 'Temporary 6-digit PIN',
      generate: 'Generate',
      nameRequired: 'Enter a name',
      contractorRequired: 'Select a contractor',
      submit: 'Create user',
      created: 'User created',
      credentialsTitle: 'Share these credentials',
      credentialsWarning: 'This is the only time they are shown. The user must change them on first sign-in.',
      loginId: 'Sign-in',
      secretPassword: 'Password',
      secretPin: 'PIN',
      copyCredentials: 'Copy credentials',
      credentialsCopied: 'Credentials copied',
    },
    editUser: { title: 'Edit user', name: 'Full name', phone: 'Phone number', updated: 'User updated' },
    reset: {
      title: 'Reset credential',
      resetPassword: 'Reset password',
      resetPin: 'Reset PIN',
      newPassword: 'New temporary password',
      newPin: 'New temporary 6-digit PIN',
      submit: 'Reset',
      done: 'Credential reset',
      forUser: (name: string) => `Set a new temporary credential for ${name}. They must change it on next sign-in.`,
    },
    toggle: {
      disable: 'Disable',
      enable: 'Enable',
      disableTitle: 'Disable this user?',
      enableTitle: 'Enable this user?',
      disableBody: (name: string) => `${name} will be signed out and will not be able to sign in.`,
      enableBody: (name: string) => `${name} will be able to sign in again.`,
      disabled: 'User disabled',
      enabled: 'User enabled',
    },
    contractors: {
      title: 'Contractors',
      create: 'New contractor',
      edit: 'Edit contractor',
      name: 'Company name',
      contactName: 'Contact person',
      phone: 'Phone',
      nameRequired: 'Enter a name',
      emptyTitle: 'No contractors yet',
      emptyBody: 'Create a contractor to add supervisors and drivers.',
      address: 'Address',
      notes: 'Notes',
      searchPlaceholder: 'Search contractors',
      searchLabel: 'Search contractors',
      statusFilter: 'Status',
      columns: { name: 'Name', contact: 'Contact', vehicles: 'Vehicles', drivers: 'Drivers', status: 'Status' },
      suspend: 'Suspend',
      activate: 'Activate',
      suspendTitle: 'Suspend this contractor?',
      activateTitle: 'Activate this contractor?',
      suspendBody: (name: string) =>
        `${name} will be suspended. Every supervisor and driver of this contractor is signed out immediately and cannot sign in until it is activated again. No data is deleted.`,
      activateBody: (name: string) =>
        `${name} will be active again and its users can sign in. Users who were disabled individually stay disabled.`,
      back: 'Contractors',
      notFound: 'Contractor not found.',
      summary: 'Summary',
      createdOn: 'Created',
      supervisors: 'Supervisors',
      noSupervisors: 'No supervisors yet.',
      noVehicles: 'No vehicles yet.',
      noDrivers: 'No drivers yet.',
      vehicleCount: (n: number) => `${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
      driverCount: (n: number) => `${n} ${n === 1 ? 'driver' : 'drivers'}`,
      viewAll: 'View all',
      open: 'Open',
      created: 'Contractor created',
      updated: 'Contractor updated',
      suspended: 'Contractor suspended',
      activated: 'Contractor activated',
    },
  },
  // Module 11: the Super admin sign-in page, forced password change and idle timeout. Calm and visibly not a client login.
  platformAuth: {
    label: 'Super admin console',
    loginTitle: 'Super admin sign-in',
    loginIntro: 'For the people who run ConvoyPass. If you manage a company workspace, sign in on the main page instead.',
    email: 'Email',
    password: 'Password',
    show: 'Show password',
    hide: 'Hide password',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    // The ONE message for a wrong password, an unknown email, a workspace account and a disabled super admin: nothing to enumerate.
    mismatch: "These details don't match a super admin account.",
    network: 'Could not reach the server. Check your connection and try again.',
    tooMany: 'Too many attempts. Wait a few minutes and try again.',
    invalidEmail: 'Enter a valid email address.',
    passwordRequired: 'Enter your password.',
    reauthNotice: 'For your security, sign in again to continue. You will return to where you were.',
    idleNotice: 'You were signed out after 30 minutes without activity.',
    changePassword: {
      title: 'Choose a new password',
      forcedIntro: 'You are using a temporary password. Choose your own before you continue.',
      intro: 'Use a long, unique password and keep it in a password manager.',
      current: 'Current password',
      new: 'New password',
      confirm: 'Confirm new password',
      submit: 'Change password',
      submitting: 'Changing…',
      back: 'Back to the console',
      rulesLabel: 'Password requirements',
      rules: { length: '14 or more characters', notEmail: 'Not your email address', notCommon: 'Not a common password' },
      mismatch: 'The two passwords do not match.',
      currentWrong: 'That is not your current password.',
      currentRequired: 'Enter your current password.',
      recentLogin: 'Please sign in again, then change your password.',
      failed: 'Could not change the password. Try again.',
      done: 'Password changed',
    },
    signup: {
      link: 'Create a super admin account',
      title: 'Create a super admin account',
      intro: 'This account can create workspaces and their admins for every client. Use a company mailbox and a strong password.',
      name: 'Full name',
      email: 'Email',
      password: 'Password',
      confirm: 'Confirm password',
      rulesLabel: 'Password requirements',
      submit: 'Create account',
      submitting: 'Creating…',
      nameRequired: 'Enter your name.',
      mismatch: 'The two passwords do not match.',
      weak: 'Choose a password that meets every requirement.',
      disabledTitle: 'Signup is turned off',
      disabledBody: 'New super admin accounts cannot be created here right now. Sign in, or ask the person who runs ConvoyPass.',
      checking: 'Checking…',
      backToSignIn: 'Back to sign-in',
      failed: 'Could not create the account. Try again.',
    },
    topBar: { changePassword: 'Change password', signOut: 'Sign out' },
    idle: {
      title: 'Still there?',
      body: (seconds: number) => `You will be signed out in ${seconds} ${seconds === 1 ? 'second' : 'seconds'} because there has been no activity.`,
      stay: 'Stay signed in',
      signOut: 'Sign out now',
    },
    reauthGoToSignIn: 'Sign in on the sign-in page instead',
  },
  // Module 9: the platform operator console (/platform). Operators only; never shown to a client workspace.
  platform: {
    label: 'Super admin console',
    nav: { overview: 'Overview', workspaces: 'Workspaces', invites: 'Invites' },
    navLabel: 'Super admin console navigation',
    overview: {
      title: 'Overview',
      invitesHeading: 'Setup invites',
      tenantsHeading: 'Workspaces',
      unused: 'Unused',
      claimed: 'Being used now',
      used: 'Used',
      expired: 'Expired',
      tenants: 'Workspaces',
      newWorkspace: 'New workspace',
      newInvite: 'Create an invite',
      viewInvites: 'View invites',
      viewWorkspaces: 'View workspaces',
    },
    invites: {
      title: 'Setup invites',
      intro: 'One invite is one link and creates one new workspace and its first admin.',
      alternative: 'Alternative: let the client choose their own password by sending an invite link. To set up the admin yourself, use New workspace.',
      newTitle: 'New invite',
      company: 'Company name',
      companyHint: 'Shown on the setup page. Optional.',
      email: 'Expected admin email',
      emailHint: 'Lock the invite to this email so only they can complete setup.',
      expiry: 'Expires after',
      days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
      create: 'Create invite',
      creating: 'Creating…',
      invalidEmail: 'Enter a valid email address.',
      companyTooLong: 'Use at most 80 characters.',
      resultTitle: 'Invite ready',
      oneTimeWarning: 'This link is shown only once. Anyone who opens it first becomes the admin.',
      linkLabel: 'Setup link',
      copyLink: 'Copy link',
      linkCopied: 'Link copied',
      copyFailed: 'Could not copy. Select the link and copy it by hand.',
      whatsapp: 'Send by WhatsApp',
      emailButton: 'Send by email',
      closeCard: 'Done, hide the link',
      expiresOn: (date: string) => `Expires on ${date}`,
      lockedTo: (email: string) => `Locked to ${email}`,
      message: (p: { company?: string | undefined; link: string; expires: string }) =>
        [
          p.company ? `ConvoyPass setup for ${p.company}` : 'ConvoyPass setup',
          '',
          `Open this link to set up your workspace: ${p.link}`,
          '',
          `The link expires on ${p.expires}.`,
          "Open the link on the device you'll use as admin.",
        ].join('\n'),
      emailSubject: (company?: string) => (company ? `Your ConvoyPass setup link for ${company}` : 'Your ConvoyPass setup link'),
      listHeading: 'All invites',
      filterLabel: 'Status',
      allStatuses: 'All statuses',
      status: { unused: 'Unused', claimed: 'In use', used: 'Used', expired: 'Expired' },
      columns: { invite: 'Invite', company: 'Company', lock: 'Locked to', status: 'Status', expires: 'Expires', workspace: 'Workspace' },
      noCompany: 'No company name',
      noLock: 'Anyone with the link',
      empty: 'No invites yet.',
      emptyFiltered: 'No invites with this status.',
      loadMore: 'Load more',
      revoke: 'Revoke',
      revokeTitle: 'Revoke this invite?',
      revokeBody: (prefix: string) => `The link for invite ${prefix} will stop working. This cannot be undone.`,
      revoked: 'Invite revoked',
      loadFailed: 'Could not load invites.',
    },
    reauth: {
      title: 'Sign in again',
      body: 'For your security, confirm your password to continue. Your request will be sent again right after.',
      password: 'Password',
      confirm: 'Confirm and continue',
      wrong: 'That password is not right.',
      failed: 'Could not confirm your password. Try again.',
    },
    workspaces: {
      title: 'Workspaces',
      intro: 'Company workspaces and their admins. Counts only: client business data is never shown here.',
      search: 'Search workspaces',
      searchPlaceholder: 'Company, admin or email',
      newButton: 'New workspace',
      columns: { name: 'Company', created: 'Created', timezone: 'Timezone', admins: 'Admins', users: 'Users', vehicles: 'Vehicles' },
      notSignedIn: 'Not signed in yet',
      adminsCount: (active: number, total: number) => (active === total ? `${total}` : `${active} of ${total} active`),
      empty: 'No workspaces yet. Create one with New workspace, or send an invite link.',
      noMatch: 'No workspace matches your search.',
      loadMore: 'Load more',
      loadFailed: 'Could not load workspaces.',
      back: 'All workspaces',
      newTitle: 'New workspace',
      newIntro: 'Creates the workspace and its first admin with a temporary password you hand over once.',
      company: 'Company name',
      timezone: 'Timezone',
      timezoneHint: 'Start typing to search, e.g. Asia/Colombo.',
      timezoneInvalid: 'Choose a timezone from the list.',
      adminName: 'Admin name',
      adminEmail: 'Admin email',
      companyInvalid: 'Use 2 to 80 characters.',
      nameInvalid: 'Use 2 to 60 characters.',
      emailInvalid: 'Enter a valid email address.',
      create: 'Create workspace',
      creating: 'Creating…',
      cancel: 'Cancel',
    },
    detail: {
      created: 'Created',
      timezone: 'Timezone',
      countsOnly: 'Counts only',
      users: 'Users',
      vehicles: 'Vehicles',
      adminsTitle: 'Admins',
      addAdmin: 'Add admin',
      addAdminTitle: 'Add an admin',
      addAdminIntro: 'Creates another admin for this workspace with a temporary password.',
      columns: { name: 'Name', email: 'Email', status: 'Status', firstSignIn: 'First sign-in', lastSignIn: 'Last sign-in' },
      signedIn: 'Signed in',
      notSignedIn: 'Not signed in yet',
      mustChange: 'Must choose a new password',
      never: 'Never',
      edit: 'Edit name',
      editTitle: 'Edit admin name',
      editName: 'Name',
      save: 'Save',
      saved: 'Name saved',
      reset: 'Reset credentials',
      resetTitle: 'Reset credentials?',
      resetBody: (name: string) => `${name} will be signed out everywhere and given a new temporary password, shown once, and must choose a new one at next sign-in.`,
      disable: 'Disable',
      enable: 'Enable',
      disableTitle: 'Disable this admin?',
      disableBody: (name: string) => `${name} will be signed out and cannot sign in until you enable the account again.`,
      enableTitle: 'Enable this admin?',
      enableBody: (name: string) => `${name} will be able to sign in again.`,
      disabled: 'Admin disabled',
      enabled: 'Admin enabled',
      notFound: 'This workspace was not found.',
      loadFailed: 'Could not load this workspace.',
      noAdmins: 'This workspace has no admins.',
    },
    credentials: {
      title: 'Hand over these credentials',
      warning: 'This password is shown only once. Share it now: it cannot be shown again, only reset.',
      loginUrl: 'Login URL',
      email: 'Admin email',
      password: 'Temporary password',
      show: 'Show',
      hide: 'Hide',
      copy: 'Copy',
      copied: 'Copied',
      copyAll: 'Copy all as message',
      whatsapp: 'Send by WhatsApp',
      emailButton: 'Send by email',
      confirm: "I've shared it",
      copyFailed: 'Could not copy. Show the value and copy it by hand.',
      emailSubject: (company: string) => `Your ConvoyPass login for ${company}`,
      message: (p: { company: string; loginUrl: string; email: string; password: string }) =>
        [
          `ConvoyPass login for ${p.company}`,
          '',
          `Login: ${p.loginUrl}`,
          `Email: ${p.email}`,
          `Temporary password: ${p.password}`,
          '',
          'You will be asked to choose a new password when you sign in. Please do not forward this message.',
        ].join('\n'),
    },
    forbiddenOperator: 'Operator accounts cannot open client workspace pages.',
  },
} as const
