import { useMemo, useState, type FormEvent } from 'react'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { strings } from '@/lib/strings'
import { DEFAULT_SETUP_TIMEZONE, timezoneList } from '@/lib/timezones'

const t = strings.platform.workspaces
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export interface NewWorkspaceValues {
  companyName: string
  timezone: string
  adminName: string
  adminEmail: string
}

/** Plain controlled form. The values go to `onSubmit` and nowhere else; the admin's password is generated by the server. */
export function NewWorkspaceForm({ onSubmit, onCancel }: { onSubmit: (v: NewWorkspaceValues) => Promise<void>; onCancel: () => void }) {
  const zones = useMemo(() => timezoneList(), [])
  const [companyName, setCompany] = useState('')
  const [timezone, setTimezone] = useState(DEFAULT_SETUP_TIMEZONE)
  const [adminName, setName] = useState('')
  const [adminEmail, setEmail] = useState('')
  const [busy, setBusy] = useState(false)
  const [errors, setErrors] = useState<Partial<Record<keyof NewWorkspaceValues, string>>>({})

  const submit = async (e: FormEvent) => {
    e.preventDefault()
    const v = { companyName: companyName.trim(), timezone: timezone.trim(), adminName: adminName.trim(), adminEmail: adminEmail.trim().toLowerCase() }
    const next: typeof errors = {}
    if (v.companyName.length < 2 || v.companyName.length > 80) next.companyName = t.companyInvalid
    if (!zones.includes(v.timezone)) next.timezone = t.timezoneInvalid
    if (v.adminName.length < 2 || v.adminName.length > 60) next.adminName = t.nameInvalid
    if (!EMAIL.test(v.adminEmail)) next.adminEmail = t.emailInvalid
    setErrors(next)
    if (Object.keys(next).length > 0) return
    setBusy(true)
    try {
      await onSubmit(v)
    } finally {
      setBusy(false)
    }
  }

  return (
    <form noValidate onSubmit={(e) => void submit(e)} aria-label={t.newTitle} className="space-y-4 rounded-xl border border-slate-200 bg-white p-5">
      <div>
        <h2 className="text-base font-semibold">{t.newTitle}</h2>
        <p className="text-sm text-slate-500">{t.newIntro}</p>
      </div>
      <div className="grid gap-4 sm:grid-cols-2">
        <Input label={t.company} value={companyName} onChange={(e) => setCompany(e.target.value)} error={errors.companyName} autoComplete="off" />
        <Input label={t.timezone} list="platform-timezones" hint={t.timezoneHint} value={timezone} onChange={(e) => setTimezone(e.target.value)} error={errors.timezone} autoComplete="off" autoCapitalize="none" spellCheck={false} />
        <datalist id="platform-timezones">
          {zones.map((z) => <option key={z} value={z} />)}
        </datalist>
        <Input label={t.adminName} value={adminName} onChange={(e) => setName(e.target.value)} error={errors.adminName} autoComplete="off" />
        <Input label={t.adminEmail} type="email" value={adminEmail} onChange={(e) => setEmail(e.target.value)} error={errors.adminEmail} autoComplete="off" />
      </div>
      <div className="flex gap-2">
        <Button type="submit" loading={busy}>{busy ? t.creating : t.create}</Button>
        <Button variant="secondary" onClick={onCancel} disabled={busy}>{t.cancel}</Button>
      </div>
    </form>
  )
}
