import { lazy } from 'react'

export const LoginPage = lazy(() => import('@/features/auth/LoginPage'))
export const ChangePasswordPage = lazy(() => import('@/features/auth/ChangePasswordPage'))
export const RolePlaceholder = lazy(() => import('@/features/auth/RolePlaceholder'))
export const VehicleRoute = lazy(() => import('@/features/passes/VehicleRoute'))
export const DriverHome = lazy(() => import('@/features/passes/DriverHome'))
export const SettingsPage = lazy(() => import('@/features/admin/SettingsPage'))
export const AdminLayout = lazy(() => import('@/features/admin/AdminLayout'))
export const UsersPage = lazy(() => import('@/features/admin/UsersPage'))
export const ContractorsPage = lazy(() => import('@/features/admin/ContractorsPage'))
export const ContractorDetailPage = lazy(() => import('@/features/admin/ContractorDetailPage'))
export const VehiclesPage = lazy(() => import('@/features/vehicles/VehiclesPage'))
export const DriversPage = lazy(() => import('@/features/drivers/DriversPage'))
export const QrLabelsPage = lazy(() => import('@/features/qr/QrLabelsPage'))
export const SupervisorLayout = lazy(() => import('@/features/supervisor/SupervisorLayout'))
export const SupervisorHome = lazy(() => import('@/features/supervisor/SupervisorHome'))
export const ApprovalsPage = lazy(() => import('@/features/supervisor/ApprovalsPage'))
export const ReviewPage = lazy(() => import('@/features/supervisor/ReviewPage'))
export const OfficerLayout = lazy(() => import('@/features/officer/OfficerLayout'))
export const OfficerQueue = lazy(() => import('@/features/officer/OfficerQueue'))
export const PassesPage = lazy(() => import('@/features/admin/PassesPage'))
